spring:
  datasource:
    url: jdbc:h2:file:./data/crypt
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false